In [2]:
import numpy as np

## Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# Lista en python
[1,2,3,4,5,7,12]

# Lista en numpy
a = np.array([1,2,3,4,5,7,12])

In [7]:
# Reemplazar un valor especifico del arreglo
a[2] = 10
print(a)

[ 1  2 10  4  5  7 12]


In [8]:
# secuencia con python normal
print(list(range(3,10)))

# secuencia numerica con numpy
print(np.arange(3,10))

[3, 4, 5, 6, 7, 8, 9]
[3 4 5 6 7 8 9]


In [9]:
# secuencia de numeros entre un valor (A) y otro (B) con una longitud de (C)
# np.linspace(A,B,C)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Multidimentional arrays (two dimensions or more)

In [10]:
np.zeros((5,2)) # matrix 5: number of rows, 2: number of columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
# matrix of 3 rows and 3 columns: 1 , 2, 3 is the first row
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [12]:
n[0,2] # access to row 1, column 3

np.int64(3)

In [13]:
n[0] # access to entire first row

array([1, 2, 3])

In [14]:
n[2] = [1, 1, 1] # change the entire last row by [1,1,1]

In [15]:
n[2]

array([1, 1, 1])

In [16]:
n[:,1] # access an entire column (column number two)

array([2, 5, 1])

In [17]:
n[:,2] = [0, 1, 2] # changes an entire column (column number three)

In [18]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

## Randomly generated arrays

In [19]:
np.random.seed(2) # set seed
np.random.rand(5,2)# introduces a random matrix/array with 5 rows and two columns

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
# normal distribution randn
np.random.seed(2) # set seed
np.random.randn(5,2)# introduces a random matrix/array with 5 rows and two columns

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:
# integer between range
np.random.seed(2) # set seed
np.random.randint(low = 0, high = 100, size = (5,2))# introduces a random matrix/array with 5 rows and two columns

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations (element by element)

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
10 + (a * 2) # multiplies every element of the array by two and then add 10

array([10, 12, 14, 16, 18])

In [24]:
b = (10 + (a * 2)) ** 2 / 100

In [25]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [29]:
a

array([0, 1, 2, 3, 4])

In [30]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [27]:
a >= 2

array([False, False,  True,  True,  True])

In [28]:
a > b

array([False, False,  True,  True,  True])

In [ ]:
a[a>b]

## Summarizing operations

In [31]:
a.sum()

np.int64(10)

In [32]:
a.mean()

np.float64(2.0)

In [33]:
a.std()

np.float64(1.4142135623730951)